#pragma once

#include <glbinding/gl/gl.h>
#include <glbinding/binding.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <SDL.h>
#include <SDL_opengl.h>
#include <iostream>
#include <sstream>
#include "Image.h"
#include "Camera.h"
#include "Shader.h"
#include "Texture.h"
#include "ResourceManager.h"
#include "Model.h"
#include "Renderer.h"

#undef GL_COLOR_BUFFER_BIT
#undef GL_ARRAY_BUFFER
#undef GL_STATIC_DRAW
#undef GL_ELEMENT_ARRAY_BUFFER
#undef GL_VERTEX_SHADER
#undef GL_FRAGMENT_SHADER
#undef GL_COMPILE_STATUS
#undef GL_FLOAT
#undef GL_TEXTURE_2D
#undef GL_TEXTURE_WRAP_S
#undef GL_CLAMP_TO_EDGE
#undef GL_TEXTURE_WRAP_T
#undef GL_TEXTURE_MIN_FILTER
#undef GL_TEXTURE_MAG_FILTER
#undef GL_LINEAR
#undef GL_RGBA
#undef GL_RGB
#undef GL_BGRA
#undef GL_UNSIGNED_BYTE
#undef GL_UNSIGNED_INT
#undef GL_TRIANGLES
#undef GL_TEXTURE0
#undef GL_DEPTH_TEST
#undef GL_DEPTH_BUFFER_BIT
#undef GL_TEXTURE1
#undef GL_ALWAYS
#undef GL_FALSE
#undef GL_LESS
#undef GL_STENCIL_TEST
#undef GL_NOTEQUAL
#undef GL_KEEP
#undef GL_REPLACE
#undef GL_STENCIL_BUFFER_BIT
#undef GL_BLEND
#undef GL_SRC_ALPHA
#undef GL_ONE_MINUS_SRC_ALPHA
#undef GL_CULL_FACE
#undef GL_FRONT
#undef GL_FRAMEBUFFER
#undef GL_FRAMEBUFFER_COMPLETE
#undef GL_COLOR_ATTACHMENT0
#undef GL_RENDERBUFFER
#undef GL_DEPTH24_STENCIL8
#undef GL_DEPTH_STENCIL_ATTACHMENT
#undef GL_TEXTURE_CUBE_MAP
#undef GL_TEXTURE_CUBE_MAP_POSITIVE_X
#undef GL_TEXTURE_WRAP_R
#undef GL_TRUE
#undef GL_LEQUAL
#undef GL_TEXTURE5
#undef GL_GEOMETRY_SHADER
#undef GL_POINTS
#undef GL_PROGRAM_POINT_SIZE
#undef GL_INT
#undef GL_FRONT_AND_BACK
#undef GL_LINE
#undef GL_CW
#undef GL_CCW